name: Release Pipeline v01

on:
  release:
    types:
      - published

# Use created if you want the workflow to run when any kind of release is created, including drafts and prereleases.
# Use published if you want the workflow to run only when a full release (non-draft, non-prerelease) is published.

jobs:
  build-and-publish:
    runs-on: windows-latest

    steps:

    - name: Download Artifact
      id: download_artifact
      run: |
        # Download the artifact with a wildcard for the version number
        nuget_package=$(find . -name "Greg.Xrm.Command.Interfaces.*.nupkg" -type f)
        echo "Downloaded NuGet package: $nuget_package"
        echo "nuget_package=$nuget_package" >> $GITHUB_OUTPUT

    - name: Publish to NuGet
      run: |
        # Get the downloaded NuGet package path
        nuget_package_path=${{ steps.download_artifact.outputs.nuget_package }}
        
        # Push the NuGet package to NuGet.org
        nuget push $nuget_package_path -ApiKey ${{ secrets.NUGET_APIKEY }}
